using System.Globalization;
using Avalonia;
using Avalonia.Media;

namespace LiveMarkdown.Avalonia;

/// <summary>
/// Centralizes creation and drawing of Mermaid label text for native Avalonia renderers.
/// </summary>
/// <remarks>
/// Renderer code should use this helper instead of constructing <see cref="FormattedText"/> directly,
/// so Markdown/HTML-like parsing, font selection, and baseline-ish placement stay consistent across
/// flowchart, state, sequence, class, and future diagram renderers.
/// </remarks>
internal static class MermaidTextRenderer
{
    private static readonly FontFamily CodeFontFamily = FontFamily.Parse("Cascadia Mono, Consolas, Menlo, monospace");

    /// <summary>
    /// Creates plain formatted text using the presenter's current font family and culture.
    /// </summary>
    public static FormattedText CreateFormattedText(
        MermaidPresenter presenter,
        string text,
        double fontSize,
        IBrush? brush,
        TextAlignment alignment,
        FontWeight fontWeight = default)
    {
        return new FormattedText(
            text,
            CultureInfo.CurrentCulture,
            FlowDirection.LeftToRight,
            new Typeface(presenter.FontFamily, FontStyle.Normal, fontWeight == default ? FontWeight.Normal : fontWeight),
            fontSize,
            brush)
        {
            TextAlignment = alignment,
            MaxTextWidth = double.PositiveInfinity
        };
    }

    /// <summary>
    /// Creates formatted text and applies inline style spans generated by <see cref="MermaidInlineTextParser"/>.
    /// </summary>
    /// <remarks>
    /// Span offsets are interpreted against <see cref="MermaidTextLayout.Text"/>. Inline code currently
    /// switches to a monospace family only; code background can be added later without changing parser
    /// output.
    /// </remarks>
    public static FormattedText CreateFormattedText(
        MermaidPresenter presenter,
        MermaidTextLayout layout,
        double fontSize,
        IBrush? brush,
        TextAlignment alignment,
        FontWeight fontWeight = default)
    {
        var text = CreateFormattedText(presenter, layout.Text, fontSize, brush, alignment, fontWeight);
        ApplySpans(text, layout.Spans);
        return text;
    }

    /// <summary>
    /// Draws plain text at a Mermaid layout point using the helper's placement convention.
    /// </summary>
    /// <remarks>
    /// When <paramref name="centerVertically"/> is false, <paramref name="y"/> is treated as the
    /// bottom edge of the text box. This matches several Mermaider SVG renderer coordinates that
    /// represent label baselines or lower anchors rather than top-left origins.
    /// </remarks>
    public static void DrawText(
        DrawingContext dc,
        MermaidPresenter presenter,
        string text,
        double x,
        double y,
        double fontSize,
        IBrush? brush,
        TextAlignment alignment,
        bool centerVertically = false,
        FontWeight fontWeight = default)
    {
        var ft = CreateFormattedText(presenter, text, fontSize, brush, alignment, fontWeight);
        DrawFormattedText(dc, ft, x, y, alignment, centerVertically);
    }

    /// <summary>
    /// Draws an already-created <see cref="FormattedText"/> with optional horizontal and vertical centering.
    /// </summary>
    public static void DrawFormattedText(
        DrawingContext dc,
        FormattedText text,
        double x,
        double y,
        TextAlignment alignment,
        bool centerVertically = false)
    {
        var originY = centerVertically ? y - text.Height / 2 : y - text.Height;
        var originX = alignment switch
        {
            TextAlignment.Center => x - text.Width / 2,
            TextAlignment.Right => x - text.Width,
            _ => x
        };
        dc.DrawText(text, new Point(originX, originY));
    }

    /// <summary>
    /// Parses and draws a Mermaid label that may contain inline Markdown or Mermaider HTML-like markup.
    /// </summary>
    public static void DrawInlineText(
        DrawingContext dc,
        MermaidPresenter presenter,
        string text,
        bool isMarkdown,
        double x,
        double y,
        double fontSize,
        IBrush? brush,
        TextAlignment alignment,
        bool centerVertically = false,
        FontWeight fontWeight = default)
    {
        var layout = MermaidInlineTextParser.Parse(text, isMarkdown);
        var ft = CreateFormattedText(presenter, layout, fontSize, brush, alignment, fontWeight);
        DrawFormattedText(dc, ft, x, y, alignment, centerVertically);
    }

    /// <summary>
    /// Draws an inline label centered in a rounded background rectangle.
    /// </summary>
    /// <remarks>
    /// This is used for edge labels and similar callouts where text should remain legible over lines.
    /// Width and height are based on the parsed formatted text plus symmetric padding.
    /// </remarks>
    public static void DrawTextWithBackground(
        DrawingContext dc,
        MermaidPresenter presenter,
        string text,
        bool isMarkdown,
        double centerX,
        double centerY,
        double fontSize,
        IBrush? textBrush,
        IBrush? backgroundBrush,
        IPen? backgroundPen,
        double padding,
        double radius,
        TextAlignment alignment = TextAlignment.Center)
    {
        var layout = MermaidInlineTextParser.Parse(text, isMarkdown);
        var ft = CreateFormattedText(presenter, layout, fontSize, textBrush, alignment);
        var width = ft.Width + padding * 2;
        var height = ft.Height + padding;

        var bgRect = new Rect(centerX - width / 2, centerY - height / 2, width, height);
        dc.DrawRectangle(backgroundBrush, backgroundPen, bgRect, radius, radius);
        dc.DrawText(ft, new Point(bgRect.X + padding, bgRect.Y + padding / 2));
    }

    private static void ApplySpans(FormattedText text, IReadOnlyList<MermaidTextSpan> spans)
    {
        foreach (var span in spans)
        {
            if (span.Length <= 0)
            {
                continue;
            }

            if (span.Style.HasFlag(MermaidTextStyle.Bold))
            {
                text.SetFontWeight(FontWeight.Bold, span.Start, span.Length);
            }

            if (span.Style.HasFlag(MermaidTextStyle.Italic))
            {
                text.SetFontStyle(FontStyle.Italic, span.Start, span.Length);
            }

            if (span.Style.HasFlag(MermaidTextStyle.Code))
            {
                text.SetFontFamily(CodeFontFamily, span.Start, span.Length);
            }

            var decorations = GetDecorations(span.Style);
            if (decorations is not null)
            {
                text.SetTextDecorations(decorations, span.Start, span.Length);
            }
        }
    }

    private static TextDecorationCollection? GetDecorations(MermaidTextStyle style)
    {
        var underline = style.HasFlag(MermaidTextStyle.Underline);
        var strikethrough = style.HasFlag(MermaidTextStyle.Strikethrough);

        if (!underline && !strikethrough)
        {
            return null;
        }

        var decorations = new TextDecorationCollection();
        if (underline)
        {
            decorations.AddRange(TextDecorations.Underline);
        }

        if (strikethrough)
        {
            decorations.AddRange(TextDecorations.Strikethrough);
        }

        return decorations;
    }
}