using System.Globalization;
using Avalonia;
using Avalonia.Media;
using Mermaider.Models;
using Point = Avalonia.Point;

namespace LiveMarkdown.Avalonia;

/// <summary>
/// Native Avalonia renderer for Mermaid treemap diagrams.
/// </summary>
/// <remarks>
/// Treemap layout is generated by Mermaider's SVG renderer from the parsed hierarchy. This renderer
/// ports that rectangle layout locally and keeps the chart size and palette on a styleable renderer
/// part instead of adding treemap-only tokens to <see cref="MermaidPresenter"/>.
/// </remarks>
public sealed class TreemapRenderer : MermaidRenderer
{
    private static readonly IReadOnlyList<Color> DefaultNodePalette =
    [
        Color.Parse("#4e79a7"), Color.Parse("#f28e2b"), Color.Parse("#e15759"), Color.Parse("#76b7b2"),
        Color.Parse("#59a14f"), Color.Parse("#edc948"), Color.Parse("#b07aa1"), Color.Parse("#ff9da7"),
        Color.Parse("#9c755f"), Color.Parse("#bab0ac")
    ];

    // SVG-compatible thresholds: labels are suppressed in tiny rectangles where they become noise.
    private const double MinimumLabelWidth = 30;
    private const double MinimumLabelHeight = 16;
    private const double MinimumValueHeight = 30;
    private const double MinimumChildHeight = 10;

    // Stable visual constants from the SVG renderer. They affect paint opacity and label placement.
    private const byte RootFillAlpha = 0xCC;
    private const byte ChildFillAlpha = 0x99;
    private const byte ValueTextAlpha = 0xCC;
    private const double RectCornerRadius = 3;
    private const double RectStrokeThickness = 1;
    private const double LabelTopOffset = 12;
    private const double ValueLabelOffset = 14;

    /// <summary>
    /// Defines the <see cref="ChartWidth"/> property.
    /// </summary>
    public static readonly StyledProperty<double> ChartWidthProperty =
        AvaloniaProperty.Register<TreemapRenderer, double>(nameof(ChartWidth), 600);

    /// <summary>
    /// Width of the fixed treemap plotting area.
    /// </summary>
    public double ChartWidth
    {
        get => GetValue(ChartWidthProperty);
        set => SetValue(ChartWidthProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="ChartHeight"/> property.
    /// </summary>
    public static readonly StyledProperty<double> ChartHeightProperty =
        AvaloniaProperty.Register<TreemapRenderer, double>(nameof(ChartHeight), 400);

    /// <summary>
    /// Height of the fixed treemap plotting area.
    /// </summary>
    public double ChartHeight
    {
        get => GetValue(ChartHeightProperty);
        set => SetValue(ChartHeightProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="CellPadding"/> property.
    /// </summary>
    public static readonly StyledProperty<double> CellPaddingProperty =
        AvaloniaProperty.Register<TreemapRenderer, double>(nameof(CellPadding), 2);

    /// <summary>
    /// Padding inset applied around every generated treemap rectangle.
    /// </summary>
    public double CellPadding
    {
        get => GetValue(CellPaddingProperty);
        set => SetValue(CellPaddingProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="HeaderHeight"/> property.
    /// </summary>
    public static readonly StyledProperty<double> HeaderHeightProperty =
        AvaloniaProperty.Register<TreemapRenderer, double>(nameof(HeaderHeight), 20);

    /// <summary>
    /// Height reserved for a parent node label before laying out its children.
    /// </summary>
    public double HeaderHeight
    {
        get => GetValue(HeaderHeightProperty);
        set => SetValue(HeaderHeightProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="LabelFontSize"/> property.
    /// </summary>
    public static readonly StyledProperty<double> LabelFontSizeProperty =
        AvaloniaProperty.Register<TreemapRenderer, double>(nameof(LabelFontSize), 14);

    /// <summary>
    /// Font size used for treemap node labels.
    /// </summary>
    public double LabelFontSize
    {
        get => GetValue(LabelFontSizeProperty);
        set => SetValue(LabelFontSizeProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="ValueFontSize"/> property.
    /// </summary>
    public static readonly StyledProperty<double> ValueFontSizeProperty =
        AvaloniaProperty.Register<TreemapRenderer, double>(nameof(ValueFontSize), 12);

    /// <summary>
    /// Font size used for numeric value labels.
    /// </summary>
    public double ValueFontSize
    {
        get => GetValue(ValueFontSizeProperty);
        set => SetValue(ValueFontSizeProperty, value);
    }

    /// <summary>
    /// Defines the <see cref="NodePalette"/> property.
    /// </summary>
    public static readonly StyledProperty<IReadOnlyList<Color>> NodePaletteProperty =
        AvaloniaProperty.Register<TreemapRenderer, IReadOnlyList<Color>>(nameof(NodePalette), DefaultNodePalette);

    /// <summary>
    /// Repeating palette used for treemap node rectangles.
    /// </summary>
    public IReadOnlyList<Color> NodePalette
    {
        get => GetValue(NodePaletteProperty);
        set => SetValue(NodePaletteProperty, value);
    }

    private readonly record struct Style(
        double ChartWidth,
        double ChartHeight,
        double CellPadding,
        double HeaderHeight,
        double LabelFontSize,
        double ValueFontSize,
        IReadOnlyList<Color> NodePalette
    );

    /// <summary>
    /// Calculates the desired size for the diagram using this renderer part's current styled values.
    /// </summary>
    public Size MeasureDiagram(TreemapDiagram diagram)
    {
        var style = CreateStyleSnapshot();
        return new Size(style.ChartWidth, style.ChartHeight);
    }

    /// <summary>
    /// Draws a treemap diagram using this renderer part's current styled values.
    /// </summary>
    public void RenderDiagram(DrawingContext dc, MermaidPresenter presenter, TreemapDiagram diagram)
    {
        var style = CreateStyleSnapshot();
        if (diagram.Roots.Count == 0)
        {
            return;
        }

        var rects = new List<TreeRect>();
        Squarify(diagram.Roots, 0, 0, style.ChartWidth, style.ChartHeight, rects, 0, style);
        foreach (var rect in rects)
        {
            DrawRect(dc, presenter, style, rect);
        }
    }

    /// <inheritdoc/>
    protected override bool ShouldInvalidatePresenterMeasure(AvaloniaProperty property) =>
        property.Name is nameof(ChartWidth) or nameof(ChartHeight);

    private Style CreateStyleSnapshot() =>
        new(ChartWidth, ChartHeight, CellPadding, HeaderHeight, LabelFontSize, ValueFontSize, NodePalette);

    private static void Squarify(
        IReadOnlyList<TreemapNode> nodes,
        double x,
        double y,
        double width,
        double height,
        List<TreeRect> rects,
        int depth,
        Style style)
    {
        var total = 0.0;
        foreach (var node in nodes)
        {
            total += node.ComputedValue;
        }

        if (total <= 0 || width <= 0 || height <= 0)
        {
            return;
        }

        var sorted = new List<TreemapNode>(nodes);
        sorted.Sort(static (a, b) => b.ComputedValue.CompareTo(a.ComputedValue));
        LayoutRow(sorted, x, y, width, height, total, rects, depth, style);
    }

    private static void LayoutRow(
        List<TreemapNode> nodes,
        double x,
        double y,
        double width,
        double height,
        double total,
        List<TreeRect> rects,
        int depth,
        Style style)
    {
        if (nodes.Count == 0 || total <= 0)
        {
            return;
        }

        var isWide = width >= height;
        var currentX = x;
        var currentY = y;

        foreach (var node in nodes)
        {
            var fraction = node.ComputedValue / total;
            var rectWidth = isWide ? width * fraction : width;
            var rectHeight = isWide ? height : height * fraction;
            var color = GetPaletteColor(style.NodePalette, rects.Count);

            rects.Add(
                new TreeRect(
                    currentX + style.CellPadding,
                    currentY + style.CellPadding,
                    rectWidth - style.CellPadding * 2,
                    rectHeight - style.CellPadding * 2,
                    node.Label,
                    node.ComputedValue,
                    color,
                    depth));

            if (node.Children.Count > 0)
            {
                var innerY = currentY + style.CellPadding + style.HeaderHeight;
                var innerHeight = rectHeight - style.CellPadding * 2 - style.HeaderHeight;
                if (innerHeight > MinimumChildHeight)
                {
                    Squarify(
                        node.Children,
                        currentX + style.CellPadding,
                        innerY,
                        rectWidth - style.CellPadding * 2,
                        innerHeight,
                        rects,
                        depth + 1,
                        style);
                }
            }

            if (isWide)
            {
                currentX += rectWidth;
            }
            else
            {
                currentY += rectHeight;
            }
        }
    }

    private static void DrawRect(DrawingContext dc, MermaidPresenter presenter, Style style, TreeRect rect)
    {
        if (rect.Width <= 0 || rect.Height <= 0)
        {
            return;
        }

        var fill = new SolidColorBrush(WithAlpha(rect.Color, rect.Depth == 0 ? RootFillAlpha : ChildFillAlpha));
        var stroke = new Pen(presenter.BackgroundBrush ?? Brushes.Transparent, RectStrokeThickness);
        var bounds = new Rect(rect.X, rect.Y, rect.Width, rect.Height);

        dc.DrawRectangle(fill, stroke, bounds, RectCornerRadius, RectCornerRadius);

        if (rect.Width <= MinimumLabelWidth || rect.Height <= MinimumLabelHeight)
        {
            return;
        }

        var textX = rect.X + rect.Width / 2;
        var textY = rect.Y + LabelTopOffset;
        MermaidTextRenderer.DrawText(
            dc,
            presenter,
            rect.Label,
            textX,
            textY,
            style.LabelFontSize,
            Brushes.White,
            TextAlignment.Center,
            centerVertically: true,
            FontWeight.SemiBold);

        if (rect.Height > MinimumValueHeight)
        {
            MermaidTextRenderer.DrawText(
                dc,
                presenter,
                rect.Value.ToString("0.##", CultureInfo.InvariantCulture),
                textX,
                textY + ValueLabelOffset,
                style.ValueFontSize,
                new SolidColorBrush(Color.FromArgb(ValueTextAlpha, 255, 255, 255)),
                TextAlignment.Center,
                centerVertically: true);
        }
    }

    private static Color GetPaletteColor(IReadOnlyList<Color> palette, int index) =>
        palette.Count > 0 ? palette[index % palette.Count] : DefaultNodePalette[index % DefaultNodePalette.Count];

    private static Color WithAlpha(Color color, byte alpha) => new(alpha, color.R, color.G, color.B);

    private sealed record TreeRect(double X, double Y, double Width, double Height, string Label, double Value, Color Color, int Depth);
}